//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriFarmProj.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    [DataContract]
    public partial class tblBidding
    {
        [DataMember]
        public int Biddingid { get; set; }
        [DataMember]
        public Nullable<int> Requestid { get; set; }
        [DataMember]
        public Nullable<int> Bidderid { get; set; }
        [DataMember]
        public Nullable<int> InitalPrce { get; set; }
        [DataMember]
        public Nullable<int> CurrentBidPrice { get; set; }
        [DataMember]
        public Nullable<int> PreviousBidPrice { get; set; }
        [DataMember]
        public Nullable<System.DateTime> BidCloseTime { get; set; }
        [DataMember]
        public Nullable<int> ApprovalAdminId { get; set; }
    
        public virtual tblAdmin tblAdmin { get; set; }
        public virtual tblBidder tblBidder { get; set; }
        public virtual tblCropRequest tblCropRequest { get; set; }
    }
}
