//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriFarmProj.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class tblContactU
    {
        [DataMember]
        public int RequestToken { get; set; }
        [DataMember]
        public string Email { get; set; }
        [DataMember]
        public string ContactName { get; set; }
        [DataMember]
        public string RequestType { get; set; }
        [DataMember]
        public string message { get; set; }
        [DataMember]
        public string status { get; set; }
        [DataMember]
        public Nullable<int> ApprovalAdminId { get; set; }
    
        public virtual tblAdmin tblAdmin { get; set; }
    }
}
