//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriFarmProj.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class tblInsuranceClaim
    {
        [DataMember]
        public int Cliamid { get; set; }
        [DataMember]
        public Nullable<int> PolicyNo { get; set; }
        [DataMember]
        public string CauseOfClaim { get; set; }
        [DataMember]
        public Nullable<System.DateTime> DateOfLoss { get; set; }
        [DataMember]
        public Nullable<System.DateTime> DateOfClaim { get; set; }
        [DataMember]
        public Nullable<int> AmountClaimed { get; set; }
        [DataMember]
        public string ApprovalStatus { get; set; }
        [DataMember]
        public Nullable<int> ApprovalAdminId { get; set; }
    
        public virtual tblAdmin tblAdmin { get; set; }
        public virtual tblInsurance tblInsurance { get; set; }
    }
}
