//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriFarmProj.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class tblInsurance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInsurance()
        {
            this.tblInsuranceClaims = new HashSet<tblInsuranceClaim>();
        }

        [DataMember]
        public int PolicyNo { get; set; }
        [DataMember]
        public Nullable<int> Farmerid { get; set; }
        [DataMember]
        public string CompanyName { get; set; }
        [DataMember]
        public string Season { get; set; }
        [DataMember]
        public string Year { get; set; }
        [DataMember]
        public string Crop { get; set; }
        [DataMember]
        public Nullable<int> SumInsured { get; set; }
        [DataMember]
        public Nullable<System.DateTime> DateOfInsurance { get; set; }
        [DataMember]
        public Nullable<decimal> Area { get; set; }
    
        public virtual tblFarmer tblFarmer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInsuranceClaim> tblInsuranceClaims { get; set; }
    }
}
